import React, { useEffect, useState } from 'react';
import { MessageSquare, ChevronLeft, Zap, Calendar, Database } from 'lucide-react';
import { motion } from 'motion/react';

interface Discussion {
  title: string;
  desc: string;
  date: string;
  fullPath: string;
}

export default function Discussions() {
  const [discussions, setDiscussions] = useState<Discussion[]>([]);
  const [selectedDisc, setSelectedDisc] = useState<Discussion | null>(null);
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [isSummarizing, setIsSummarizing] = useState(false);

  useEffect(() => {
    const fetchDiscussions = async () => {
      try {
        const data = await globalThis.electronAPI.getRecentDiscussions();
        setDiscussions(data);
        setLoading(false);
      } catch (err) {
        console.error('Error fetching discussions:', err);
      }
    };
    fetchDiscussions();
  }, []);

  const handleSelect = async (disc: any) => {
    setSelectedDisc(disc);
    const text = await globalThis.electronAPI.readFile(disc.fullPath);
    setContent(text);
  };

  const [summary, setSummary] = useState<string | null>(null);

  const handleSummarize = async () => {
    setIsSummarizing(true);
    // Real Gemini call would go here
    setTimeout(() => {
      setSummary("Linguistic synthesis complete: This discussion centers on the phonetic drift of labio-velars in Proto-Indo-European, specifically focusing on the *kʷ and *gʷ shifts in Anatolian vs. Hellenic branches. Cross-referenced with Struktur library [Hittite_Phonology.pdf].");
      setIsSummarizing(false);
    }, 2000);
  };

  if (loading) return <div className="animate-pulse h-64 bg-surface-container rounded-lg" />;

  if (selectedDisc) {
    return (
      <motion.div 
        initial={{ opacity: 0, x: 20 }}
        animate={{ opacity: 1, x: 0 }}
      >
        <button 
          onClick={() => setSelectedDisc(null)}
          className="flex items-center gap-2 text-primary font-label text-[10px] uppercase tracking-widest mb-8 hover:underline group"
        >
          <ChevronLeft size={14} className="group-hover:-translate-x-1 transition-transform" /> Back to Archive
        </button>
        
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          <div className="lg:col-span-8 bg-surface-container-low p-8 border border-outline-variant/10">
            <header className="mb-8 border-b border-outline-variant/10 pb-6 flex justify-between items-start">
              <div>
                <h2 className="font-headline text-3xl mb-2">{selectedDisc.title}</h2>
                <div className="flex gap-4 text-[10px] font-label text-outline uppercase tracking-widest">
                  <span className="flex items-center gap-1"><Calendar size={12} /> {selectedDisc.date}</span>
                  <span className="flex items-center gap-1"><Database size={12} /> Panglossia Log</span>
                </div>
              </div>
              <button 
                onClick={handleSummarize}
                disabled={isSummarizing}
                className="flex items-center gap-2 bg-secondary text-on-secondary px-4 py-2 font-label text-[10px] uppercase tracking-widest hover:opacity-90 transition-opacity disabled:opacity-50"
              >
                <Zap size={12} /> {isSummarizing ? 'Analyzing...' : 'Analyze with Sources'}
              </button>
            </header>
            
            <div className="prose prose-invert max-w-none h-[calc(100vh-350px)] overflow-y-auto pr-4 custom-scrollbar">
              <pre className="whitespace-pre-wrap font-body text-on-surface/80 text-sm leading-relaxed">
                {content}
              </pre>
            </div>
          </div>

          <aside className="lg:col-span-4 space-y-6">
            <div className="bg-surface-container-high p-6 border border-outline-variant/10">
              <h4 className="font-label text-[10px] uppercase tracking-[0.2em] text-primary mb-4">Dialogue Meta</h4>
              <p className="text-xs text-outline leading-loose italic">
                This discussion was generated by the Panglossia engine. It contains deep linguistic analysis and reconstructed phonetic data.
              </p>
            </div>
            {(isSummarizing || summary) && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-primary-container/10 p-6 border border-primary/20"
              >
                <h4 className="font-label text-[10px] uppercase tracking-[0.2em] text-primary mb-4">Gemini Synthesis</h4>
                <p className="text-xs text-on-surface-variant leading-relaxed">
                  {isSummarizing ? 'Requesting AI synthesis of the linguistic evidence...' : summary}
                </p>
              </motion.div>
            )}
          </aside>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div 
      initial={{ opacity: 0, filter: 'blur(10px)' }}
      animate={{ opacity: 1, filter: 'blur(0px)' }}
      className="max-w-[1400px] mx-auto"
    >
      <header className="mb-12 border-b border-outline-variant/10 pb-8">
        <h1 className="text-4xl font-headline font-light text-on-surface mb-2">Linguistic Dialogues</h1>
        <p className="text-outline font-body italic opacity-80 max-w-2xl">
          Archive of your interactions with external linguistic intelligence.
        </p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {discussions.map((disc) => (
          <button
            key={disc.fullPath}
            onClick={() => handleSelect(disc)}
            className="p-8 bg-surface-container-low border border-outline-variant/10 hover:border-primary/40 group transition-all text-left relative overflow-hidden"
          >
            <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
              <MessageSquare size={80} />
            </div>
            <div className="flex items-center gap-2 text-primary/60 font-label text-[9px] uppercase tracking-widest mb-4">
              <Calendar size={12} /> {disc.date}
            </div>
            <h3 className="font-headline text-2xl mb-4 group-hover:text-primary transition-colors">{disc.title}</h3>
            <p className="text-xs text-outline line-clamp-3 font-body opacity-60 leading-relaxed mb-6">
              {disc.desc}
            </p>
            <div className="flex items-center gap-2 text-[10px] font-label uppercase tracking-widest text-primary opacity-0 group-hover:opacity-100 transition-opacity">
              Interrogate Log <ChevronLeft size={12} className="rotate-180" />
            </div>
          </button>
        ))}
      </div>
    </motion.div>
  );
}
